# Generated by Django 4.0.4 on 2022-06-07 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0003_todo_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='image',
        ),
    ]
